env: production
database:
  auto-migrate: true
errors:
  insufficient-arguments: "§cNot enough arguments"
  internal-server-error: "§cInternal server error"
  invalid-argument: '§cInvalid argument provided: "%s"'
formatters:
  date: "yyyy-MM-dd HH:mm"
statistics:
  enabled: true
  remote: "https://goldenage.keii.dev"
  serverId: -1
  serverSecret: ""
betaprotect:
  enabled: true
  commands:
    betaprotect:
      inspect:
        on-message: "§eTurned on inspect mode"
        off-message: "§eTurned off inspect mode"
        block-title: "§f----- §eBetaProtect §f----- §e(x%x/y%y/z%z)"
        block-entry: "§e%d §f- §e%a §f%r §e#%i (%b)"
commands:
  list:
    format: "§eOnline players (${online}/${max}): ${playerList}"
    enabled: true
  seen:
    no-user: "§cThis user has never been seen."
    success-duration: "§e${player} was seen ${duration} ago."
    success-now: "§e${player} was seen now."
    success-online: "§e${player} is online."
    enabled: true
  history:
    no-user: "§cUser was not found"
    player-title: "§eLogin history for ${player}"
    player-row: "§e${date} - ${duration}"
    global-title: "§eLogin history for everyone"
    global-row: "§e${player} logged in ${date} - ${duration}"
    limit: 10
    enabled: true
